package com.rewardshopplanner.data;

import com.google.gson.Gson;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import lombok.Getter;

/**
 * The bundled reward data generated by scripts/generate-data.ps1.
 */
@Getter
public class RewardData
{
	private final Map<String, Currency> currencies;
	private final Map<String, Activity> activities;
	private final Map<String, Reward> rewards;

	public RewardData(List<Currency> currencies, List<Activity> activities, List<Reward> rewards)
	{
		this.currencies = index(currencies, Currency::getId);
		this.activities = index(activities, Activity::getId);
		this.rewards = index(rewards, Reward::getName);
	}

	public static RewardData load(Gson gson) throws IOException
	{
		return new RewardData(
			Arrays.asList(read(gson, "currencies.json", Currency[].class)),
			Arrays.asList(read(gson, "activities.json", Activity[].class)),
			Arrays.asList(read(gson, "rewards.json", Reward[].class)));
	}

	public Reward getReward(String name)
	{
		return rewards.get(name);
	}

	private static <T> T read(Gson gson, String file, Class<T> type) throws IOException
	{
		try (InputStream in = RewardData.class.getResourceAsStream(file))
		{
			if (in == null)
			{
				throw new IOException("Missing bundled data file: " + file);
			}
			try (Reader reader = new InputStreamReader(in, StandardCharsets.UTF_8))
			{
				return gson.fromJson(reader, type);
			}
		}
	}

	private static <T> Map<String, T> index(List<T> list, Function<T, String> key)
	{
		Map<String, T> map = new LinkedHashMap<>();
		for (T t : list)
		{
			map.put(key.apply(t), t);
		}
		return Collections.unmodifiableMap(map);
	}
}
